version: '1'
services:
  api:
    image: file-reader
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - logs:/usr/src/app

  web-cli:
    image: sample-express-app
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge